
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Label label1;
	private global::Gtk.HBox hbox4;
	private global::Gtk.VBox vbox6;
	private global::Gtk.Button A1;
	private global::Gtk.Button B1;
	private global::Gtk.Button C1;
	private global::Gtk.VBox vbox7;
	private global::Gtk.Button A2;
	private global::Gtk.Button B2;
	private global::Gtk.Button C2;
	private global::Gtk.VBox vbox8;
	private global::Gtk.Button A3;
	private global::Gtk.Button B3;
	private global::Gtk.Button C3;
	private global::Gtk.Button Reset;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Tres en Raya");
		this.vbox1.Add (this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		w1.Padding = ((uint)(5));
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.A1 = new global::Gtk.Button ();
		this.A1.CanFocus = true;
		this.A1.Name = "A1";
		this.A1.UseUnderline = true;
		this.A1.Label = "";
		this.vbox6.Add (this.A1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.A1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.B1 = new global::Gtk.Button ();
		this.B1.CanFocus = true;
		this.B1.Name = "B1";
		this.B1.UseUnderline = true;
		this.B1.Label = "";
		this.vbox6.Add (this.B1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.B1]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.C1 = new global::Gtk.Button ();
		this.C1.CanFocus = true;
		this.C1.Name = "C1";
		this.C1.UseUnderline = true;
		this.C1.Label = "";
		this.vbox6.Add (this.C1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.C1]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		this.hbox4.Add (this.vbox6);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox6]));
		w5.Position = 0;
		w5.Padding = ((uint)(5));
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.A2 = new global::Gtk.Button ();
		this.A2.CanFocus = true;
		this.A2.Name = "A2";
		this.A2.UseUnderline = true;
		this.A2.Label = "";
		this.vbox7.Add (this.A2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.A2]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.B2 = new global::Gtk.Button ();
		this.B2.CanFocus = true;
		this.B2.Name = "B2";
		this.B2.UseUnderline = true;
		this.B2.Label = "";
		this.vbox7.Add (this.B2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.B2]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.C2 = new global::Gtk.Button ();
		this.C2.CanFocus = true;
		this.C2.Name = "C2";
		this.C2.UseUnderline = true;
		this.C2.Label = "";
		this.vbox7.Add (this.C2);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.C2]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		this.hbox4.Add (this.vbox7);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox7]));
		w9.Position = 1;
		w9.Padding = ((uint)(5));
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox8 = new global::Gtk.VBox ();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.A3 = new global::Gtk.Button ();
		this.A3.CanFocus = true;
		this.A3.Name = "A3";
		this.A3.UseUnderline = true;
		this.A3.Label = "";
		this.vbox8.Add (this.A3);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.A3]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.B3 = new global::Gtk.Button ();
		this.B3.CanFocus = true;
		this.B3.Name = "B3";
		this.B3.UseUnderline = true;
		this.B3.Label = "";
		this.vbox8.Add (this.B3);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.B3]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.C3 = new global::Gtk.Button ();
		this.C3.CanFocus = true;
		this.C3.Name = "C3";
		this.C3.UseUnderline = true;
		this.C3.Label = "";
		this.vbox8.Add (this.C3);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.C3]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		this.hbox4.Add (this.vbox8);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox8]));
		w13.Position = 2;
		w13.Padding = ((uint)(5));
		this.vbox1.Add (this.hbox4);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.Reset = new global::Gtk.Button ();
		this.Reset.CanFocus = true;
		this.Reset.Name = "Reset";
		this.Reset.UseUnderline = true;
		this.Reset.Label = global::Mono.Unix.Catalog.GetString ("Nueva partida");
		this.vbox1.Add (this.Reset);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.Reset]));
		w15.PackType = ((global::Gtk.PackType)(1));
		w15.Position = 2;
		w15.Expand = false;
		w15.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 370;
		this.DefaultHeight = 183;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.A1.Clicked += new global::System.EventHandler (this.onA1Click);
		this.B1.Clicked += new global::System.EventHandler (this.onB1Click);
		this.C1.Clicked += new global::System.EventHandler (this.onC1Click);
		this.A2.Clicked += new global::System.EventHandler (this.onA2Click);
		this.B2.Clicked += new global::System.EventHandler (this.onB2Click);
		this.C2.Clicked += new global::System.EventHandler (this.onC2Click);
		this.A3.Clicked += new global::System.EventHandler (this.onA3Click);
		this.B3.Clicked += new global::System.EventHandler (this.onB3Click);
		this.C3.Clicked += new global::System.EventHandler (this.onC3Click);
		this.Reset.Clicked += new global::System.EventHandler (this.onResetClick);
	}
}
